apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-libvirt
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: cluster-api-provider-libvirt-system
